# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${env:ORGANISATION}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: exam
# "service" is the name of this project. This will also be added to your AWS resource names.
service: exam

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${env:PROVIDER_PROFILE}
  region: eu-north-1
  iam:
    role: ${env:PROVIDER_IAM_ROLE}

plugins:
  - serverless-dotenv-plugin
  # - serverless-webpack

package:
  individually: true

build:
  esbuild: false

functions:
  # getNotes:
  #   handler: functions/getNotes/index.handler
  #   events:
  #     - httpApi:
  #         path: /api/notes
  #         method: get
  # postNotes:
  #   handler: functions/postNotes/index.handler
  #   events:
  #     - httpApi:
    #       path: /api/notes
    #       method: post
  # changeNotes:
  #   handler: functions/changeNotes/index.handler
  #   events:
  #     - httpApi:
    #       path: /api/notes
    #       method: put
  # deleteNotes:
  #   handler: functions/deleteNotes/index.handler
  #   events:
  #     - httpApi:
    #       path: /api/notes
    #       method: delete
  signUp:
    handler: functions/signUp/index.handler
    events:
      - httpApi:
          path: /api/user/signup
          method: post
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: /api/user/login
          method: post

resources:
  Resources:
    notesDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-db
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema: 
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    usersDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: accounts
        AttributeDefinitions: 
          - AttributeName: username
            AttributeType: S
        KeySchema: 
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST